kind: pipeline
name: default

steps:
- name: push-private-registry
  image: plugins/docker
  settings:
    repo: registry-castor.max-heidinger.de/ical-merger
    registry: registry-castor.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request

- name: push-public-registry
  image: plugins/docker
  settings:
    repo: ghcr.io/mheidinger/iCalMergerDocker
    registry: ghcr.io
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: github_username
    password:
      from_secret: github_password
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request

- name: update-deployment
  image: plugins/webhook
  settings:
    urls: https://portainer.max-heidinger.de/api/webhooks/8ae88773-eae6-47d1-b689-3d089a0e01c1
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request
